#pragma once

#define IDC_TURTLECLASS_WINDOW 100
#define IDC_STUDENT_LIST 101
#define IDC_POINTS_EDIT 102
#define IDC_QUEUE_BUTTON 103
#define IDC_STATUS_TEXT 104
#define IDC_LOGIN_BUTTON 105
#define IDC_LOGOUT_BUTTON 106
#define IDC_CLASS_CODE_EDIT 107
#define IDC_STUDENT_ID_EDIT 108
#define IDC_PASSWORD_EDIT 109
