#!/bin/bash
# DeepSeek Daily Read-Only Audit Script
# 每日自动执行，导出审计日志并提交给 DeepSeek 进行安全审查

set -e

# 配置
TURTLECLASS_DATA_DIR="${TURTLECLASS_DATA_DIR:-/var/lib/turtleclass}"
AUDIT_EXPORT_DIR="${AUDIT_EXPORT_DIR:-/var/log/turtleclass/audit_exports}"
DEEPSEEK_API_KEY="${DEEPSEEK_API_KEY:-}"
DEEPSEEK_ENDPOINT="https://api.deepseek.com/v1/chat/completions"
RETENTION_DAYS=30

# 颜色
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}=== DeepSeek Daily Audit ===${NC}"
echo "Date: $(date)"

# 创建导出目录
mkdir -p "$AUDIT_EXPORT_DIR"

# 生成今日导出文件名
TODAY=$(date +%Y-%m-%d)
EXPORT_FILE="$AUDIT_EXPORT_DIR/audit_$TODAY.json"

# 从数据库导出审计日志（只读）
echo -e "${YELLOW}Exporting audit logs...${NC}"

# 使用 sqlite3 导出最近 24 小时的审计日志
sqlite3 "$TURTLECLASS_DATA_DIR/turtleclass.db" <<EOF > "$EXPORT_FILE"
.mode json
SELECT 
    timestamp,
    event_type,
    admin_id,
    device_id,
    class_code,
    action,
    target_type,
    target_id,
    ip_address,
    status
FROM audit_log
WHERE timestamp >= strftime('%s', 'now', '-24 hours')
ORDER BY timestamp DESC;
EOF

if [ ! -s "$EXPORT_FILE" ]; then
    echo -e "${YELLOW}No audit events in the last 24 hours${NC}"
    echo "[]" > "$EXPORT_FILE"
fi

EVENT_COUNT=$(jq length "$EXPORT_FILE")
echo -e "${GREEN}Exported $EVENT_COUNT audit events${NC}"

# 如果 DEEPSEEK_API_KEY 未设置，跳过 API 调用
if [ -z "$DEEPSEEK_API_KEY" ]; then
    echo -e "${YELLOW}DEEPSEEK_API_KEY not set. Skipping API submission.${NC}"
    echo "Audit file saved to: $EXPORT_FILE"
    exit 0
fi

# 准备提交给 DeepSeek 的分析请求
echo -e "${YELLOW}Submitting to DeepSeek for analysis...${NC}"

# 构建分析提示
PROMPT="You are a security auditor for TurtleClass, a classroom management system. 
Analyze the following audit log entries from the past 24 hours and identify:
1. Any suspicious patterns or potential security threats
2. Unusual admin activities
3. Failed authentication attempts
4. Potential data integrity issues
5. Recommendations for improving security

Audit Log (JSON format):
$(cat "$EXPORT_FILE")

Provide your analysis in JSON format with these fields:
- risk_level: (low/medium/high)
- findings: (array of security findings)
- recommendations: (array of actionable recommendations)
- summary: (brief summary)"

# 调用 DeepSeek API
RESPONSE_FILE="$AUDIT_EXPORT_DIR/deepseek_analysis_$TODAY.json"

curl -s -X POST "$DEEPSEEK_ENDPOINT" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $DEEPSEEK_API_KEY" \
    -d "{
        \"model\": \"deepseek-chat\",
        \"messages\": [
            {
                \"role\": \"system\",
                \"content\": \"You are a professional security auditor. Analyze audit logs and provide actionable security insights.\"
            },
            {
                \"role\": \"user\",
                \"content\": \"$PROMPT\"
            }
        ],
        \"temperature\": 0.3,
        \"max_tokens\": 2000
    }" | jq '.' > "$RESPONSE_FILE"

if [ $? -eq 0 ] && [ -s "$RESPONSE_FILE" ]; then
    echo -e "${GREEN}DeepSeek analysis completed${NC}"
    
    # 提取关键发现
    RISK_LEVEL=$(jq -r '.choices[0].message.content | fromjson | .risk_level // "unknown"' "$RESPONSE_FILE" 2>/dev/null || echo "unknown")
    echo "Risk Level: $RISK_LEVEL"
    
    # 保存完整报告
    REPORT_FILE="$AUDIT_EXPORT_DIR/security_report_$TODAY.md"
    cat > "$REPORT_FILE" <<EOF
# TurtleClass Daily Security Audit Report
**Date**: $TODAY
**Generated**: $(date)
**Risk Level**: $RISK_LEVEL

## DeepSeek Analysis

\`\`\`json
$(cat "$RESPONSE_FILE")
\`\`\`

## Raw Audit Data

See: $EXPORT_FILE

---
*This report was automatically generated by the DeepSeek Daily Audit script.*
EOF
    
    echo -e "${GREEN}Report saved to: $REPORT_FILE${NC}"
    
    # 可选：发送警报（如果风险等级高）
    if [ "$RISK_LEVEL" = "high" ]; then
        echo -e "${RED}HIGH RISK DETECTED! Check report: $REPORT_FILE${NC}"
        # 这里可以添加邮件/Slack 通知逻辑
    fi
else
    echo -e "${RED}Failed to get DeepSeek analysis${NC}"
fi

# 清理旧文件
echo -e "${YELLOW}Cleaning up old exports (older than $RETENTION_DAYS days)...${NC}"
find "$AUDIT_EXPORT_DIR" -name "*.json" -mtime +$RETENTION_DAYS -delete
find "$AUDIT_EXPORT_DIR" -name "*.md" -mtime +$RETENTION_DAYS -delete

echo -e "${GREEN}Daily audit complete${NC}"
